baseurl: /

title: "Udit Srivastava"
author: "Udit Srivastava"
bio-oneliner: "A Pythonista| Fond of SQL"

social-site:
    facebook: "https://www.facebook.com/shaitanudit.srivastava"
    instagram: "https://twitter.com/Udit9519"
    twitter: "https://www.instagram.com/udit_srivastav/"
    github: "https://github.com/uditsrivastava"
    
